name: Build and populate cache

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: 'https://install.lix.systems/lix/lix-installer-x86_64-linux'
          logger: pretty
          diagnostic-endpoint: ""

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update flake inputs
        run: nix flake update nixpkgs --commit-lock-file

      - name: Pull upstream changes
        run: |
          git remote add upstream https://git.lix.systems/lix-project/lix.git
          git fetch upstream
          git checkout upstream/main
          git rebase origin/main
          git push origin HEAD:main

  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}
    needs: update

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
          - os: ubuntu-24.04-arm
            system: aarch64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: 'https://install.lix.systems/lix/lix-installer-${{ matrix.system }}'
          logger: pretty
          diagnostic-endpoint: ""

      # https://git.lix.systems/lix-project/lix/issues/545
      - name: Loosen apparmor restrictions
        if: matrix.os != 'macos-latest'
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Setup Attic
        uses: ryanccn/attic-action@v0.3.2
        with:
          inputs-from: flake.lock
          endpoint: https://cache.tgirl.cloud
          cache: tgirlcloud
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build lix
        run: nix build -L .#nix
